# Board and Square Constants
SQUARE_SIZE = 150
BOARD_SIZE = SQUARE_SIZE * 8

WHITE_SENSITIVITY = 30
GREEN_SENSITIVITY = 40

WHITE_THRESHOLD = 18000
GREEN_THRESHOLD = 20000


# Demo Constants
SHOW_SQUARES = False
DEBUG = True